apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: haproxy-kubernetes-ingress
rules:
- apiGroups: [""] 
  resources: [configmaps, endpoints, nodes, pods, services, namespaces, events, serviceaccounts, secrets]
  verbs: [get, list, watch]
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: [ingresses, ingresses/status, ingressclasses]
  verbs: [get, list, watch, update]
- apiGroups: ["apps"]
  resources: [replicasets, deployments, daemonsets]
  verbs: [get, list]
- apiGroups: ["apiextensions.k8s.io"]
  resources: [customresourcedefinitions]
  verbs: [get, list, watch]
