apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: haproxy-kubernetes-ingress
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps", "services", "endpoints", "pods", "nodes", "namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "ingressclasses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["ingress.v1.haproxy.org"]
  resources: ["globals", "defaults", "backends", "tcps"]
  verbs: ["get", "list", "watch"]